"""Update Fighter and Fight relationships

Revision ID: c2132a65231b
Revises: 0afb15eeb692
Create Date: 2024-10-01 19:39:04.385450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2132a65231b'
down_revision: Union[str, None] = '0afb15eeb692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
